# Конфигурация Jekyll
theme: minima
title: Мир Звёздного пути
description: Вики фандома 'Мир Звёздного пути'
baseurl: "/Cowboy_Donor_K.github.io" # Замените на имя вашего репозитория, если не пользовательский сайт
url: "https://Cowboy_Donor_K.github.io" # Замените на ваш домен
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:title